const banner = `/**
 * marked - a markdown parser
 * Copyright (c) 2011-${new Date().getFullYear()}, Christopher Jeffrey. (MIT Licensed)
 * https://github.com/markedjs/marked
 */
/**
 * DO NOT EDIT THIS FILE
 * The code in this file is generated from files in ./src/
 */
`;

export default {
	input: "src/marked.js",
	output: {
		file: "dist/marked.esm.js",
		format: "esm",
		banner,
	},
};
